LibraryWebUI/ViewModels/Admin/AdminHomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryWebUI.ViewModels.Admin
{
    public class AdminHomeViewModel : BaseViewModel
    {
    }
}

LibraryWebUI/ViewModels/Member/MemberHomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreLibrary.Accounts;
using CoreLibrary.Inventory;
using CoreLibrary.Members;
using LibraryWebUI.Models;
using LibraryWebUI.ViewModels.Admin;

namespace LibraryWebUI.ViewModels.Member
{
    public class MemberHomeViewModel : BaseViewModel
    {
		public IQueryable<IBook> LoanedBooks { get; set; } = (new List<IBook>()).AsQueryable();
	}
}

LibraryWebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibraryWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using CoreLibrary.Searching;
using CoreLibrary.Inventory;
using CoreLibrary.Members;
using LibraryWebUI.ViewModels.Admin;
using LibraryWebUI.ViewModels;
using Microsoft.AspNetCore.Http;
using System.IO;
using CoreLibrary.Accounts;

namespace LibraryWebUI.Controllers
{
    public class AdminController : BaseController
    {
		[HttpGet]
        public IActionResult AdminLogin() {
            return View(new LoginViewModel());
		}

		//[HttpPost]
		//public IActionResult AdminLogin(LoginModel loginInfo) {
		//	IActionResult view;
		//	AccountRepository adminRepo = new AccountRepository();
		//	if (ModelState.IsValid) {
		//		if (adminRepo.VerifyAdminLogin(loginInfo.Email, loginInfo.Password)) {
		//			IAccount admin = SearchUtility.GetAccountByEmail(loginInfo.Email);
		//			Model.User = admin;
		//			view = View("AdminHome", new AdminHomeViewModel());
		//		} else {
		//			view = View(new LoginViewModel {
		//				LoginErrorInfo = new string[] { "Incorrect login information. Please try again" },
		//				LoginInfo = new LoginModel { Email = loginInfo.Email }
		//			});
		//		}
		//	} else {
		//		view = View(new LoginViewModel());
		//	}

		//	return view;
		//}

		public IActionResult AdminHome() {
			IActionResult view;

			if (this.GetUserAccount().Admin) {
				view = View(new AdminHomeViewModel());
			} else {
				view = View("AdminLogin", new LoginViewModel());
			}
			return view;
		}

		public IActionResult Inventory() {

			return View();
		}

		[HttpGet]
		public IActionResult NewBook() {
			return View(new NewBookViewModel());
		}

		[HttpPost]
		public IActionResult NewBook(Book book, IFormFile imageFile) {
			if (imageFile != null) {
				using (var stream = new MemoryStream()) {
					imageFile.CopyTo(stream);
					book.ImageBytes = stream.ToArray();
				}
			} else {
				book.ImageBytes = InventoryManager.GetItemImage(book.LibraryID);
			}
			book.LibraryID = InventoryManager.GetNewLibraryID();
			CoreLibrary.Inventory.InventoryManager.AddNewBook(book);
			NewBookViewModel viewModel = new NewBookViewModel();
			viewModel.Book = SearchUtility.GetBookByLibraryID(book.LibraryID);

			return View("NewBookResult", viewModel);
		}
		
		public IActionResult EditBook(int libraryID) {
			EditBookViewModel viewModel = new EditBookViewModel();
			viewModel.Book = SearchUtility.GetBookByLibraryID(libraryID);
			return View(viewModel);
		}

		[HttpPost]
		public IActionResult EditBookResult(Book book, IFormFile imageFile) {
			if (imageFile != null) {
				using (var stream = new MemoryStream()) {
					imageFile.CopyTo(stream);
					book.ImageBytes = stream.ToArray();
				}
			} else {
				book.ImageBytes = InventoryManager.GetItemImage(book.LibraryID);
			}
			
			InventoryManager.UpdateBook(book);
			EditBookResultViewModel viewModel = new EditBookResultViewModel();
			viewModel.Book = SearchUtility.GetBookByLibraryID(book.LibraryID);
			return View(viewModel);
		}

		[HttpGet]
		public IActionResult SpecifyBookToEdit() {
			SpecifyBookViewModel viewModel = new SpecifyBookViewModel();
			viewModel.Action = "SpecifyBookToEdit";
			return View("SpecifyBook", viewModel);
		}

		[HttpPost]
		public IActionResult SpecifyBookToEdit(int libraryID) {
			if (InventoryManager.IsValidLibraryID(libraryID)) {
				EditBookViewModel viewModel = new EditBookViewModel();
				viewModel.Book = SearchUtility.GetBookByLibraryID(libraryID);
				return View("EditBook", viewModel);
			}

			return View("SpecifyBook", new SpecifyBookViewModel {
				ErrorMessage = "Invalid Library ID",
				Action = "SpecifyBookToEdit"
			});
		}



		public IActionResult SpecifyBookToRemove(int libraryID) {
			SpecifyBookViewModel viewModel = new SpecifyBookViewModel();
			viewModel.Action = "RemoveBook";
			return View("SpecifyBook", viewModel);
		}

		public IActionResult RemoveBook(int libraryID) {
			RemoveBookViewModel viewModel = new RemoveBookViewModel();
			if (InventoryManager.IsValidLibraryID(libraryID)) {
				viewModel.Book = SearchUtility.GetBookByLibraryID(libraryID);
			} else {
				return View("SpecifyBook", new SpecifyBookViewModel {
					ErrorMessage = "Invalid Library ID",
					Action = "SpecifyBookToRemove"
				});
			}
			
			return View("RemoveBook", viewModel);
		}

		public IActionResult RemoveBookResult(int libraryID) {
			InventoryManager.RemoveBook(SearchUtility.GetBookByLibraryID(libraryID));
			return View();
		}

		[HttpGet]
		public IActionResult Search() {
			return View(new SearchViewModel());
		}

		[HttpPost]
		public IActionResult SortSearch(string sortSearchBy) {
			SearchViewModel viewModel = new SearchViewModel();
			switch (sortSearchBy) {
				case "title":
					viewModel.Books = viewModel.Books.OrderBy(book => book.Title);
					break;
				case "author":
					viewModel.Books = viewModel.Books.OrderBy(book => book.Author);
					break;
				case "libraryID":
					viewModel.Books = viewModel.Books.OrderBy(book => book.LibraryID);
					break;
				default:
					break;
			}

			return View("Search", viewModel);
		}

		[HttpPost]
		public IActionResult SearchByUserString(string searchString) {
			SearchViewModel viewModel = new SearchViewModel();
			viewModel.Books = viewModel.Books.Where(book => book.Title.ToLower().Contains(searchString.ToLower())
															|| book.Author.ToLower().Contains(searchString.ToLower())
															|| book.Genre.ToLower().Contains(searchString.ToLower())
															|| book.ISBN10.ToLower().Contains(searchString.ToLower())
															|| book.ISBN13.ToLower().Contains(searchString.ToLower())
															|| book.Description.ToLower().Contains(searchString.ToLower())
															|| book.Format.ToLower().Contains(searchString.ToLower())
															|| book.Publisher.ToLower().Contains(searchString.ToLower())
														);
			return View("Search", viewModel);
		}

		public IActionResult BookDetails(int libraryID) {
			IBook book = SearchUtility.GetBookByLibraryID(libraryID);
			BookDetailsViewModel viewModel = vmFactory.GetBookDetailsViewModel(book);
			return View(viewModel);
		}

		[HttpGet]
		public IActionResult ReturnBook() {
			return View();
		}

		[HttpPost]
		public IActionResult ReturnBook(int libraryID) {
			IBook book = SearchUtility.GetBookByLibraryID(libraryID);
			if (!book.InStock) {
				AccountManager.ReturnBook(book);
			}

			return View("Loans", new LoansViewModel());	
		}

		public IActionResult Loans() {
			return View(new LoansViewModel());
		}

    }
}

LibraryWebUI/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LibraryWebUI.Models;
using LibraryWebUI.ViewModels;
using LibraryWebUI.ViewModels.Member;
using CoreLibrary.Searching;
using CoreLibrary.Inventory;
using System.Net.Mail;
using CoreLibrary.Accounts;
using CoreLibrary.Members;

namespace LibraryWebUI.Controllers
{
    public class MemberController : BaseController
    {
		public delegate void HandleSentEmail();

		public IActionResult MemberHome() {
			IAccount user = this.GetUserAccount();
			IQueryable<IBook> books = InventoryManager.GetCheckedOutBooksByUser(this.GetUserAccount().Email).AsQueryable();
			return View(vmFactory.GetMemberHomeViewModel());
		}

		[HttpPost]
		public IActionResult BrowseInventory() {
			SearchRepository.SearchResults = SearchUtility.GetBooks().AsQueryable().OrderBy(book => book.Title);
			BrowseViewModel.CurrentPage = 1;
			return View(vmFactory.GetBrowseViewModel());
		}

		public IActionResult NewBrowseSession() {
			SearchRepository.SearchResults = SearchUtility.GetBooks().AsQueryable().OrderBy(book => book.Title);
			BrowseViewModel.CurrentPage = 1;
			return RedirectToAction("BrowseInventory", new { page = BrowseViewModel.CurrentPage });
		}

		[HttpGet]
		public IActionResult BrowseInventory(int page) {
			return View(vmFactory.GetBrowseViewModel());
		}

		public IActionResult NextPage() {
			BrowseViewModel.CurrentPage++;
			return RedirectToAction("BrowseInventory", new { page=BrowseViewModel.CurrentPage });
			//return View("BrowseInventory", new BrowseViewModel());
		}

		public IActionResult PreviousPage() {
			BrowseViewModel.CurrentPage--;
			return RedirectToAction("BrowseInventory", new { page = BrowseViewModel.CurrentPage });
		}

		public IActionResult SetResultsPerPage(int resultsPerPage) {
			BrowseViewModel.ResultsPerPage = resultsPerPage;
			BrowseViewModel.CurrentPage = 1;
			return RedirectToAction("BrowseInventory");
		}

		[HttpPost]
		public IActionResult SortSearch(string sortSearchBy) {			
			switch (sortSearchBy) {
				case "title":
					SearchRepository.SearchResults = SearchRepository.SearchResults.OrderBy(book => book.Title);
					break;
				case "author":
					SearchRepository.SearchResults = SearchRepository.SearchResults.OrderBy(book => book.Author);
					break;
				case "libraryID":
					SearchRepository.SearchResults = SearchRepository.SearchResults.OrderBy(book => book.LibraryID);
					break;
				case "genre":
					SearchRepository.SearchResults = SearchRepository.SearchResults.OrderBy(book => book.Genre);
					break;
				case "format":
					SearchRepository.SearchResults = SearchRepository.SearchResults.OrderBy(book => book.Format);
					break;
				default:
					break;
			}
			BrowseViewModel.CurrentPage = 1;

			return RedirectToAction("BrowseInventory");
			;
		}

		[HttpPost]
		public IActionResult SearchByUserString(string searchString) {
			SearchRepository.Reset();
			SearchRepository.SearchResults = SearchRepository.SearchResults.Where(book => book.Title.ToLower().Contains(searchString.ToLower())
															|| book.Author.ToLower().Contains(searchString.ToLower())
															|| book.Genre.ToLower().Contains(searchString.ToLower())
															|| book.ISBN10.ToLower().Contains(searchString.ToLower())
															|| book.ISBN13.ToLower().Contains(searchString.ToLower())
															|| book.Description.ToLower().Contains(searchString.ToLower())
															|| book.Format.ToLower().Contains(searchString.ToLower())
															|| book.Publisher.ToLower().Contains(searchString.ToLower())
														);
			BrowseViewModel.CurrentPage = 1;

			return RedirectToAction("BrowseInventory");
		}

		public IActionResult ReserveBook(int libraryID) {
			ReserveBookViewModel viewModel = this.vmFactory.GetReserveBookViewModel(SearchUtility.GetBookByLibraryID(libraryID));
			return View(viewModel);
		}

		public IActionResult AddToCart(int libraryID) {
			IBook book = SearchUtility.GetBookByLibraryID(libraryID);
			this.AddToCart(book);
			
			return View("BrowseInventory", this.vmFactory.GetBrowseViewModel());
		}

		public IActionResult Cart() {
			return View(vmFactory.GetCartViewModel());
		}

		public IActionResult BookDetails(int libraryID) {
			IBook book = SearchUtility.GetBookByLibraryID(libraryID);
			BookDetailsViewModel viewModel = this.vmFactory.GetBookDetailsViewModel(book);
			return View(viewModel);
		}

		public IActionResult Checkout() {
            this.EmailAdministrator();
            this.EmailMember();

			Cart cart = this.GetCart();
			foreach (IBook book in cart.Contents) {
				AccountManager.CheckoutBook(book, this.GetUserAccount());
			}
			cart.Empty();
			
			return View("MemberHome", this.vmFactory.GetMemberHomeViewModel());
		}
		
		[HttpPost]
		public IActionResult RemoveFromCart(int libraryID) {
			this.RemoveFromCart(SearchUtility.GetBookByLibraryID(libraryID));
			return View("Cart", this.vmFactory.GetCartViewModel());
		}

		public IActionResult AccountDetails() {
			return View();
		}

        private void EmailAdministrator()
        {
            try
            {
                MailMessage mail = new MailMessage();
                SmtpClient smtpServer = new SmtpClient("smtp.gmail.com");

                mail.From = new MailAddress("mattslibrarymanager@gmail.com");
                mail.To.Add("mattslibrarymanager@gmail.com");
                mail.Subject = "Book Reservation!";

                string bodyMessage = $"Member: {this.GetUserAccount().FirstName} {this.GetUserAccount().LastName} \n" +
                    $"Email: {this.GetUserAccount().Email}\n\n" +
                    $"Reserve these items:\n====================\n";
                foreach (IBook item in this.GetCart().Contents)
                {
                    bodyMessage += $"Item# {item.LibraryID}\n{item.Title}\n====================\n";
                }
                mail.Body = bodyMessage;

                smtpServer.Port = 587;
                smtpServer.Credentials = new System.Net.NetworkCredential("mattslibrarymanager@gmail.com", "8122Password");
                smtpServer.EnableSsl = true;

                HandleSentEmail sentEmailHandler = () => {
                    smtpServer.Dispose();
                    mail.Dispose();
                    RedirectToAction("BrowseInventory");
                };
                smtpServer.SendAsync(mail, sentEmailHandler);
            }
            catch (Exception e) {
				string message = e.Message;
			}
        }

        private void EmailMember()
        {
            try
            {
                MailMessage mail = new MailMessage();
                SmtpClient smtpServer = new SmtpClient("smtp.gmail.com");

                mail.From = new MailAddress("mattslibrarymanager@gmail.com");
                mail.To.Add(this.GetUserAccount().Email);
                mail.Subject = "Reservation Summary!";
                
                string bodyMessage = "Thank you for your order! \nYou may reply to this email at any time to set up a time for pick up or delivery.\n\nDetails:\n\n====================\n";
                foreach (IBook item in this.GetCart().Contents)
                {
                    bodyMessage += $"Library ID: {item.LibraryID}\n{item.Title}\n by: {item.Author}\n====================\n";
                }

                bodyMessage += "\n\nYou may reply to this email at any time if you have questions or to cancel your order.";
                mail.Body = bodyMessage;

                smtpServer.Port = 587;
                smtpServer.Credentials = new System.Net.NetworkCredential("mattslibrarymanager", "8122Password");
                smtpServer.EnableSsl = true;

                HandleSentEmail sentEmailHandler = () => {
                    smtpServer.Dispose();
                    mail.Dispose();
                    RedirectToAction("BrowseInventory");
                };
                smtpServer.SendAsync(mail, sentEmailHandler);
            }
            catch (Exception e) {
				string message = e.Message;
			}
        }



	}
}

LibraryWebUI/Views/Shared/AdminHome.cshtml
@model LibraryWebUI.ViewModels.Admin.AdminHomeViewModel

@{
    ViewData["Title"] = "AdminHome";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>AdminHome</h2>
<p>Welcome, @Model.LoggedInAdmin.FirstName @Model.LoggedInAdmin.LastName!</p>

LibraryWebUI/Views/Shared/Index.cshtml
@modelvmFactory.GetViewModel<LoginViewModel>()

@{ 
	ViewData["Title"] = "Home";
	ViewData["StyleSheet"] = "index.css";
	Layout = "~/Views/Shared/_MemberLayout.cshtml";
}

<div id="welcome-container">
	<h1 id="welcome">Welcome to my personal library!</h1>
</div>

	<div id="login-container">
		<form id="login-form" asp-controller="Home" asp-action="DirectLogin" method="post">
			<div class="login-verification-info">
				@foreach (string error in Model.LoginErrorInfo) {
					error.ToString();
				}
			</div>
			<div asp-validation-summary="All"></div>
			<div class="form-group">
				<label asp-for="@Model.LoginInfo.Email">Email address</label>
				<input asp-for="@Model.LoginInfo.Email" type="email" class="form-control" placeholder="Enter Email">
			</div>
			<div class="form-group">
				<label asp-for="@Model.LoginInfo.Password">Password</label>
				<input asp-for="@Model.LoginInfo.Password" type="password" class="form-control" placeholder="Enter Password">
			</div>
			<div id="submit-login-container">
				<button type="submit" class="btn btn-primary text-center btn-submit-form">Submit</button>
			</div>
			
		</form>
        </div>

		<div id="create-account-container">
			<div class="text-center">
				<form asp-action="CreateAccount" method="get">
					<label style="display: block;">Not a Member?</label>
					<input type="submit" class="btn btn-md" value="Create Account!" />
				</form>
			</div>
		</div>	

LibraryWebUI/Views/Shared/MemberHome.cshtml
@model LibraryWebUI.ViewModels.Member.MemberHomeViewModel
@using LibraryWebUI.Models
@using CoreLibrary.Inventory
@using CoreLibrary.Searching

@{
	ViewData["Title"] = "Home";
	ViewData["StyleSheet"] = "member-home.css";
	Layout = "~/Views/Shared/_MemberLayout.cshtml";
}

<h2 id="welcome-message">Welcome, @Model.UserAccount.FirstName @Model.UserAccount.LastName!</h2>

<!-- Mobile Content -->
<div class="mobile-content">


    @if (Model.UserAccount != null && Model.LoanedBooks.Count() > 0)
    {
        <h4><span id="loaned-books-title" class="bold underline">Your Checked Out Books:</span></h4>
        <div class="row">
            @foreach (IBook book in Model.LoanedBooks)
            {
                <div class="col-xs-3">
                    <a href="@Url.Action("BookDetails", "Member", new { libraryID = @book.LibraryID })">
                        <img id="loaned-item-image" class="img-rounded img-responsive text-center" src="@($"data:image/png;base64,{Convert.ToBase64String(book.ImageBytes)}")">
                    </a>
                    <h5 id="due-date" class="text-center">
                        @if (DateTime.Today.Day >= InventoryManager.GetDueDate(book.LibraryID).Day)
                        {
                            <font id="overdue">OVERDUE</font>
                        }
                        else
                        {
                            @:Due: @(InventoryManager.GetDueDate(book.LibraryID).ToString("MM/dd"))
                        }
                    </h5>
                </div>
            }
        </div>
    }
</div>


	<!-- Checked out books -->
	@if (Model.UserAccount != null && Model.LoanedBooks.Count() > 0) {
		<div id="loaned-books" class="col-xs-2">
			<h4 class="text-center"><span id="loaned-books-title" class="bold underline">Your Checked Out Books:</span></h4>
			<div class="row">
				@foreach (IBook book in Model.LoanedBooks) {
					<div class="col-xs-12">
						<hr id="loaned-item-divider" />
						<a href="@Url.Action("BookDetails", "Member", new { libraryID=@book.LibraryID })">
							<img id="loaned-item-image" class="img-rounded img-responsive text-center" src="@($"data:image/png;base64,{Convert.ToBase64String(book.ImageBytes)}")">
						</a>
						<h5 id="due-date" class="text-center">
							@if (DateTime.Today.Day >= InventoryManager.GetDueDate(book.LibraryID).Day) {
								<font id="overdue">OVERDUE</font>
							} else {
								@:Due: @(InventoryManager.GetDueDate(book.LibraryID).ToString("MM/dd"))
							}
						</h5>
					</div>
				}
			</div>
		</div>
	}

	<!-- Recently Added -->
	<h4>Recently Added</h4>
	<div class="row">
		@foreach (IBook book in SearchUtility.GetBooks().OrderByDescending(book => book.LibraryID).Take(4)) {
			<div class="col-xs-2">
				<a href="@Url.Action("BookDetails", "Member", new { libraryID=@book.LibraryID })">
					<img class="img-rounded img-responsive text-center" src="@($"data:image/png;base64,{Convert.ToBase64String(book.ImageBytes)}")">
				</a>
			</div>
		}
	</div>






LibraryWebUI/Views/Shared/Test.cshtml
@model string[]
@{
    ViewData["Title"] = "Test";
}

<h2>Test</h2>

@foreach (string thing in Model) {
	@thing
	@: <br />

}

LibraryWebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"]</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="~/css/master.css" />
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
					<li><a asp-area="" asp-controller="Admin" asp-action="Inventory">Inventory</a></li>
					<li><a asp-area="" asp-controller="Admin" asp-action="Search">Search</a></li>
				</ul>
				@if (Model.UserAccount != null) {
					<a class="navbar-text navbar-right" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
					<a class="navbar-text navbar-right" asp-area="" asp-controller="Admin" asp-action="Loans">Loans</a>
				}
			</div>
		</div>
	</nav>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; 2018 - LibraryWebUI</p>
		</footer>
	</div>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("Scripts", required: false)
</body>
</html>

LibraryWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"]</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="~/css/master.css" />
	@if (ViewData["StyleSheet"] != null && (string) ViewData["StyleSheet"] != "") {
		<link rel="stylesheet" href="~/css/@ViewData["StyleSheet"]" />
	}
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div id="nav" class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Member" asp-action="BrowseInventory">Browse</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - LibraryWebUI</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>